# SEE: https://cloud.google.com/appengine/docs/standard/go/config/appref?hl=ja
runtime: nodejs18
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 2
  min_instances: 1

handlers:
  - url: /.*
    secure: always # httpsのみ許可
    script: auto   # next.jsに何のファイルをロードするかを依存する

# yarn gcp-build コマンドで利用される
build_env_variables:
  ENV: 'production'