name: deploy-staging
run-name: Deploy Staging by @${{ github.actor }}
on:
  push:
    # branches:
    #   - develop 

jobs:
  deploy-production:
    name: "Deploy Staging"
    uses: "./.github/workflows/deploy_workflow.yaml"
    with:
      environment: staging 
      app_yaml: app-staging.yaml
    secrets:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      GOOGLE_CREDENTIALS_KMS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_STAGING }}