name: deploy
run-name: 'Deploy by @{{github.actor}}'
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      app_yaml:
        type: string
        description: Path to app.yaml file
        required: true
      dispatch_yaml:
        type: string
        description: Path to dispatch.yaml file
        required: false
    secrets:
      GOOGLE_CREDENTIALS:
        description: Google Cloud credentials for deployment
        required: true
      GOOGLE_CREDENTIALS_KMS:
        description: Google Cloud credentials for KMS
        required: true
      GH_PERSONAL_ACCESS_TOKEN:
        description: GitHub personal access toke to clone infrastructure repository
        required: true
jobs:
  build:
    uses: ./.github/workflows/build_workflow.yaml
  deploy:
    name: GAE deploy
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/decrypt_secrets
        with:
          google_credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_KMS }}'
          gh_personal_access_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
          environment: '${{ inputs.environment }}'
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Deploy an App Engine app
        uses: google-github-actions/deploy-appengine@v1
        with:
          deliverables: '${{ inputs.app_yaml }}'
          flags: '--no-cache'
      - name: "Dispatch App Engine"
        if: ${{ inputs.dispatch_yaml != '' }}
        run: cp ${{ inputs.dispatch_yaml }} dispatch.yaml && gcloud app deploy dispatch.yaml --quiet
